version: '3.7'

services:
  node:
    build:
      context: ./
      target: node
    container_name: docker_node
    ports:
      - '3000:3000'
    tty: true
    volumes:
      - .:/app

  mailer:
    image: schickling/mailcatcher
    container_name: mailcatcher
    ports:
      - '1080:1080'
      - '1025:1025'
