name: "🐛 Rapport de bug"
description: Signaler un bug reproductible.
title: "🐛 <title>"
labels: ["🐛 bug"]
body:
  - type: markdown
    attributes:
      value: Merci de lire et de suivre les instructions avant de soumettre votre bug
  - type: markdown
    attributes:
      value: |
        - Pensez à vérifier que votre bug n'a pas déjà été déclaré
  - type: textarea
    id: description
    attributes:
      label: "Description du problème"
      description: Une description claire et concise du bug.
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: "URL de la page"
    validations:
      required: false
  - type: textarea
    id: reproduce
    attributes:
      label: "Reproduction du problème"
      description: Étapes pour reproduire le problème.
      placeholder: |
        1. Aller sur '...'
        2. Cliquer sur '....'
        3. Défiler jusqu'à '....'
        4. Voir l'erreur
      render: bash
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: "Attendu"
      description: Une description claire et concise de ce que vous attendiez.
    validations:
      required: false
  - type: input
    id: browser
    attributes:
      label: "Informations sur le navigateur, OS, ..."
      description: Merci de mettre un lien de [whatsmybrowser](https://www.whatsmybrowser.org/)
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: "Contexte supplémentaire"
      description: Ajoutez ici tout autre contexte ou capture d'écran concernant le bug.
      render: bash
    validations:
      required: false
