name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:

jobs:
  deploy:
    name: 'Deployment'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup node'
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      - name: 'Build docker image'
        run: docker-compose build

      - name: 'Start container'
        run: docker-compose up -d

      - name: 'List container'
        run: docker ps

      - name: 'Shell container'
        shell: 'script -q -e -c "bash {0}"'
        run: |
          docker exec docker_node sh

      - name: 'Install dependencies'
        run: yarn install

      - name: 'run lint'
        run: yarn lint

      - name: 'Launch application'
        run: yarn build

      - name: 'Exit container'
        if: always()
        run: exit

      - name: 'Stop container'
        if: always()
        run: docker-compose down
