name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:

jobs:
  deploy:
    name: 'Deployment'
    runs-on: 'ubuntu-latest'
    env:
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup node'
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      - name: 'Install dependencies'
        run: yarn install

      - name: 'run lint'
        run: yarn lint

      - name: 'Launch application'
        uses: docker_node
        run: yarn dev

      - name: 'Test curl'
        run: curl "http://localhost:3000"
